/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Crypto Investment Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get crypto market data
 */
export const getMarketDataQueryLimitDefault = 50;
export const getMarketDataQueryOffsetDefault = 0;

export const GetMarketDataQueryParams = zod.object({
  limit: zod.coerce.number().default(getMarketDataQueryLimitDefault),
  offset: zod.coerce.number().default(getMarketDataQueryOffsetDefault),
});

export const GetMarketDataResponse = zod.object({
  data: zod.array(
    zod.object({
      id: zod.number(),
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      priceChange24h: zod.number(),
      priceChangePercent24h: zod.number(),
      marketCap: zod.number(),
      volume24h: zod.number(),
      circulatingSupply: zod.number(),
      rank: zod.number(),
      logoUrl: zod.string().nullish(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Get asset details
 */
export const GetAssetDetailsParams = zod.object({
  symbol: zod.coerce.string(),
});

export const GetAssetDetailsResponse = zod.object({
  id: zod.number(),
  symbol: zod.string(),
  name: zod.string(),
  price: zod.number(),
  priceChange24h: zod.number(),
  priceChangePercent24h: zod.number(),
  marketCap: zod.number(),
  volume24h: zod.number(),
  circulatingSupply: zod.number(),
  rank: zod.number(),
  logoUrl: zod.string().nullish(),
});

/**
 * @summary Get portfolio holdings
 */
export const GetPortfolioResponse = zod.object({
  holdings: zod.array(
    zod.object({
      id: zod.number(),
      symbol: zod.string(),
      name: zod.string(),
      quantity: zod.number(),
      averageBuyPrice: zod.number(),
      currentPrice: zod.number(),
      currentValue: zod.number(),
      profitLoss: zod.number(),
      profitLossPercent: zod.number(),
      logoUrl: zod.string().nullish(),
    }),
  ),
  totalValue: zod.number(),
  totalProfitLoss: zod.number(),
  totalProfitLossPercent: zod.number(),
});

/**
 * @summary Add a holding to portfolio
 */
export const AddHoldingBody = zod.object({
  symbol: zod.string(),
  quantity: zod.number(),
  averageBuyPrice: zod.number(),
});

/**
 * @summary Update a portfolio holding
 */
export const UpdateHoldingParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateHoldingBody = zod.object({
  quantity: zod.number().optional(),
  averageBuyPrice: zod.number().optional(),
});

export const UpdateHoldingResponse = zod.object({
  id: zod.number(),
  symbol: zod.string(),
  name: zod.string(),
  quantity: zod.number(),
  averageBuyPrice: zod.number(),
  currentPrice: zod.number(),
  currentValue: zod.number(),
  profitLoss: zod.number(),
  profitLossPercent: zod.number(),
  logoUrl: zod.string().nullish(),
});

/**
 * @summary Delete a portfolio holding
 */
export const DeleteHoldingParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteHoldingResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get watchlist items
 */
export const GetWatchlistResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.number(),
      symbol: zod.string(),
      name: zod.string(),
      price: zod.number(),
      priceChangePercent24h: zod.number(),
      logoUrl: zod.string().nullish(),
    }),
  ),
});

/**
 * @summary Add asset to watchlist
 */
export const AddToWatchlistBody = zod.object({
  symbol: zod.string(),
});

/**
 * @summary Remove item from watchlist
 */
export const RemoveFromWatchlistParams = zod.object({
  id: zod.coerce.number(),
});

export const RemoveFromWatchlistResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get all investment plans
 */
export const GetInvestmentPlansResponse = zod.object({
  plans: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      tier: zod.enum(["starter", "pro", "vip"]),
      minAmount: zod.number(),
      maxAmount: zod.number().nullish(),
      durationDays: zod.number(),
      roiPercent: zod.number(),
      description: zod.string(),
      features: zod.array(zod.string()),
    }),
  ),
});

/**
 * @summary Get all user investments
 */
export const GetUserInvestmentsResponse = zod.object({
  investments: zod.array(
    zod.object({
      id: zod.number(),
      planId: zod.number(),
      planName: zod.string(),
      tier: zod.string(),
      amount: zod.number(),
      expectedReturn: zod.number(),
      roiPercent: zod.number(),
      durationDays: zod.number(),
      status: zod.enum(["active", "completed", "cancelled"]),
      startDate: zod.string(),
      endDate: zod.string(),
      daysRemaining: zod.number(),
      progressPercent: zod.number(),
    }),
  ),
  totalInvested: zod.number(),
  totalReturns: zod.number(),
  activeCount: zod.number(),
});

/**
 * @summary Create a new investment
 */
export const CreateInvestmentBody = zod.object({
  planId: zod.number(),
  amount: zod.number(),
});

/**
 * @summary Cancel an investment
 */
export const CancelInvestmentParams = zod.object({
  id: zod.coerce.number(),
});

export const CancelInvestmentResponse = zod.object({
  success: zod.boolean(),
});
