/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Crypto Investment Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CancelInvestment200,
  CreateHolding,
  CreateInvestment,
  CreateWatchlistItem,
  CryptoAsset,
  DeleteHolding200,
  ErrorResponse,
  GetInvestmentPlans200,
  GetMarketData200,
  GetMarketDataParams,
  GetPortfolio200,
  GetUserInvestments200,
  GetWatchlist200,
  HealthStatus,
  PortfolioHolding,
  RemoveFromWatchlist200,
  UpdateHolding,
  UserInvestment,
  WatchlistItem,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get crypto market data
 */
export const getGetMarketDataUrl = (params?: GetMarketDataParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/crypto/market?${stringifiedParams}`
    : `/api/crypto/market`;
};

export const getMarketData = async (
  params?: GetMarketDataParams,
  options?: RequestInit,
): Promise<GetMarketData200> => {
  return customFetch<GetMarketData200>(getGetMarketDataUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMarketDataQueryKey = (params?: GetMarketDataParams) => {
  return [`/api/crypto/market`, ...(params ? [params] : [])] as const;
};

export const getGetMarketDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketData>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMarketDataQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketData>>> = ({
    signal,
  }) => getMarketData(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketData>>
>;
export type GetMarketDataQueryError = ErrorType<unknown>;

/**
 * @summary Get crypto market data
 */

export function useGetMarketData<
  TData = Awaited<ReturnType<typeof getMarketData>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMarketDataQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get asset details
 */
export const getGetAssetDetailsUrl = (symbol: string) => {
  return `/api/crypto/asset/${symbol}`;
};

export const getAssetDetails = async (
  symbol: string,
  options?: RequestInit,
): Promise<CryptoAsset> => {
  return customFetch<CryptoAsset>(getGetAssetDetailsUrl(symbol), {
    ...options,
    method: "GET",
  });
};

export const getGetAssetDetailsQueryKey = (symbol: string) => {
  return [`/api/crypto/asset/${symbol}`] as const;
};

export const getGetAssetDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAssetDetails>>,
  TError = ErrorType<ErrorResponse>,
>(
  symbol: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAssetDetails>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAssetDetailsQueryKey(symbol);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetDetails>>> = ({
    signal,
  }) => getAssetDetails(symbol, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!symbol,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAssetDetails>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAssetDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAssetDetails>>
>;
export type GetAssetDetailsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get asset details
 */

export function useGetAssetDetails<
  TData = Awaited<ReturnType<typeof getAssetDetails>>,
  TError = ErrorType<ErrorResponse>,
>(
  symbol: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAssetDetails>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAssetDetailsQueryOptions(symbol, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get portfolio holdings
 */
export const getGetPortfolioUrl = () => {
  return `/api/portfolio`;
};

export const getPortfolio = async (
  options?: RequestInit,
): Promise<GetPortfolio200> => {
  return customFetch<GetPortfolio200>(getGetPortfolioUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPortfolioQueryKey = () => {
  return [`/api/portfolio`] as const;
};

export const getGetPortfolioQueryOptions = <
  TData = Awaited<ReturnType<typeof getPortfolio>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPortfolio>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPortfolioQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPortfolio>>> = ({
    signal,
  }) => getPortfolio({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPortfolio>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPortfolioQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPortfolio>>
>;
export type GetPortfolioQueryError = ErrorType<unknown>;

/**
 * @summary Get portfolio holdings
 */

export function useGetPortfolio<
  TData = Awaited<ReturnType<typeof getPortfolio>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPortfolio>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPortfolioQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add a holding to portfolio
 */
export const getAddHoldingUrl = () => {
  return `/api/portfolio`;
};

export const addHolding = async (
  createHolding: CreateHolding,
  options?: RequestInit,
): Promise<PortfolioHolding> => {
  return customFetch<PortfolioHolding>(getAddHoldingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createHolding),
  });
};

export const getAddHoldingMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addHolding>>,
    TError,
    { data: BodyType<CreateHolding> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addHolding>>,
  TError,
  { data: BodyType<CreateHolding> },
  TContext
> => {
  const mutationKey = ["addHolding"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addHolding>>,
    { data: BodyType<CreateHolding> }
  > = (props) => {
    const { data } = props ?? {};

    return addHolding(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddHoldingMutationResult = NonNullable<
  Awaited<ReturnType<typeof addHolding>>
>;
export type AddHoldingMutationBody = BodyType<CreateHolding>;
export type AddHoldingMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Add a holding to portfolio
 */
export const useAddHolding = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addHolding>>,
    TError,
    { data: BodyType<CreateHolding> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addHolding>>,
  TError,
  { data: BodyType<CreateHolding> },
  TContext
> => {
  return useMutation(getAddHoldingMutationOptions(options));
};

/**
 * @summary Update a portfolio holding
 */
export const getUpdateHoldingUrl = (id: number) => {
  return `/api/portfolio/${id}`;
};

export const updateHolding = async (
  id: number,
  updateHolding: UpdateHolding,
  options?: RequestInit,
): Promise<PortfolioHolding> => {
  return customFetch<PortfolioHolding>(getUpdateHoldingUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateHolding),
  });
};

export const getUpdateHoldingMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateHolding>>,
    TError,
    { id: number; data: BodyType<UpdateHolding> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateHolding>>,
  TError,
  { id: number; data: BodyType<UpdateHolding> },
  TContext
> => {
  const mutationKey = ["updateHolding"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateHolding>>,
    { id: number; data: BodyType<UpdateHolding> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateHolding(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateHoldingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateHolding>>
>;
export type UpdateHoldingMutationBody = BodyType<UpdateHolding>;
export type UpdateHoldingMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Update a portfolio holding
 */
export const useUpdateHolding = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateHolding>>,
    TError,
    { id: number; data: BodyType<UpdateHolding> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateHolding>>,
  TError,
  { id: number; data: BodyType<UpdateHolding> },
  TContext
> => {
  return useMutation(getUpdateHoldingMutationOptions(options));
};

/**
 * @summary Delete a portfolio holding
 */
export const getDeleteHoldingUrl = (id: number) => {
  return `/api/portfolio/${id}`;
};

export const deleteHolding = async (
  id: number,
  options?: RequestInit,
): Promise<DeleteHolding200> => {
  return customFetch<DeleteHolding200>(getDeleteHoldingUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteHoldingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteHolding>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteHolding>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteHolding"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteHolding>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteHolding(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteHoldingMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteHolding>>
>;

export type DeleteHoldingMutationError = ErrorType<unknown>;

/**
 * @summary Delete a portfolio holding
 */
export const useDeleteHolding = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteHolding>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteHolding>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteHoldingMutationOptions(options));
};

/**
 * @summary Get watchlist items
 */
export const getGetWatchlistUrl = () => {
  return `/api/watchlist`;
};

export const getWatchlist = async (
  options?: RequestInit,
): Promise<GetWatchlist200> => {
  return customFetch<GetWatchlist200>(getGetWatchlistUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWatchlistQueryKey = () => {
  return [`/api/watchlist`] as const;
};

export const getGetWatchlistQueryOptions = <
  TData = Awaited<ReturnType<typeof getWatchlist>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWatchlist>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWatchlistQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchlist>>> = ({
    signal,
  }) => getWatchlist({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWatchlist>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWatchlistQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWatchlist>>
>;
export type GetWatchlistQueryError = ErrorType<unknown>;

/**
 * @summary Get watchlist items
 */

export function useGetWatchlist<
  TData = Awaited<ReturnType<typeof getWatchlist>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWatchlist>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWatchlistQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add asset to watchlist
 */
export const getAddToWatchlistUrl = () => {
  return `/api/watchlist`;
};

export const addToWatchlist = async (
  createWatchlistItem: CreateWatchlistItem,
  options?: RequestInit,
): Promise<WatchlistItem> => {
  return customFetch<WatchlistItem>(getAddToWatchlistUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWatchlistItem),
  });
};

export const getAddToWatchlistMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addToWatchlist>>,
    TError,
    { data: BodyType<CreateWatchlistItem> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addToWatchlist>>,
  TError,
  { data: BodyType<CreateWatchlistItem> },
  TContext
> => {
  const mutationKey = ["addToWatchlist"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addToWatchlist>>,
    { data: BodyType<CreateWatchlistItem> }
  > = (props) => {
    const { data } = props ?? {};

    return addToWatchlist(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddToWatchlistMutationResult = NonNullable<
  Awaited<ReturnType<typeof addToWatchlist>>
>;
export type AddToWatchlistMutationBody = BodyType<CreateWatchlistItem>;
export type AddToWatchlistMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Add asset to watchlist
 */
export const useAddToWatchlist = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addToWatchlist>>,
    TError,
    { data: BodyType<CreateWatchlistItem> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addToWatchlist>>,
  TError,
  { data: BodyType<CreateWatchlistItem> },
  TContext
> => {
  return useMutation(getAddToWatchlistMutationOptions(options));
};

/**
 * @summary Remove item from watchlist
 */
export const getRemoveFromWatchlistUrl = (id: number) => {
  return `/api/watchlist/${id}`;
};

export const removeFromWatchlist = async (
  id: number,
  options?: RequestInit,
): Promise<RemoveFromWatchlist200> => {
  return customFetch<RemoveFromWatchlist200>(getRemoveFromWatchlistUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getRemoveFromWatchlistMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFromWatchlist>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFromWatchlist>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["removeFromWatchlist"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFromWatchlist>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return removeFromWatchlist(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFromWatchlistMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFromWatchlist>>
>;

export type RemoveFromWatchlistMutationError = ErrorType<unknown>;

/**
 * @summary Remove item from watchlist
 */
export const useRemoveFromWatchlist = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFromWatchlist>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeFromWatchlist>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getRemoveFromWatchlistMutationOptions(options));
};

/**
 * @summary Get all investment plans
 */
export const getGetInvestmentPlansUrl = () => {
  return `/api/investments/plans`;
};

export const getInvestmentPlans = async (
  options?: RequestInit,
): Promise<GetInvestmentPlans200> => {
  return customFetch<GetInvestmentPlans200>(getGetInvestmentPlansUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetInvestmentPlansQueryKey = () => {
  return [`/api/investments/plans`] as const;
};

export const getGetInvestmentPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof getInvestmentPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getInvestmentPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInvestmentPlansQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInvestmentPlans>>
  > = ({ signal }) => getInvestmentPlans({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInvestmentPlans>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetInvestmentPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInvestmentPlans>>
>;
export type GetInvestmentPlansQueryError = ErrorType<unknown>;

/**
 * @summary Get all investment plans
 */

export function useGetInvestmentPlans<
  TData = Awaited<ReturnType<typeof getInvestmentPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getInvestmentPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetInvestmentPlansQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all user investments
 */
export const getGetUserInvestmentsUrl = () => {
  return `/api/investments`;
};

export const getUserInvestments = async (
  options?: RequestInit,
): Promise<GetUserInvestments200> => {
  return customFetch<GetUserInvestments200>(getGetUserInvestmentsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetUserInvestmentsQueryKey = () => {
  return [`/api/investments`] as const;
};

export const getGetUserInvestmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserInvestments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserInvestments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserInvestmentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserInvestments>>
  > = ({ signal }) => getUserInvestments({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserInvestments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserInvestmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserInvestments>>
>;
export type GetUserInvestmentsQueryError = ErrorType<unknown>;

/**
 * @summary Get all user investments
 */

export function useGetUserInvestments<
  TData = Awaited<ReturnType<typeof getUserInvestments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserInvestments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserInvestmentsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new investment
 */
export const getCreateInvestmentUrl = () => {
  return `/api/investments`;
};

export const createInvestment = async (
  createInvestment: CreateInvestment,
  options?: RequestInit,
): Promise<UserInvestment> => {
  return customFetch<UserInvestment>(getCreateInvestmentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createInvestment),
  });
};

export const getCreateInvestmentMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvestment>>,
    TError,
    { data: BodyType<CreateInvestment> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInvestment>>,
  TError,
  { data: BodyType<CreateInvestment> },
  TContext
> => {
  const mutationKey = ["createInvestment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInvestment>>,
    { data: BodyType<CreateInvestment> }
  > = (props) => {
    const { data } = props ?? {};

    return createInvestment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInvestmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInvestment>>
>;
export type CreateInvestmentMutationBody = BodyType<CreateInvestment>;
export type CreateInvestmentMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a new investment
 */
export const useCreateInvestment = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvestment>>,
    TError,
    { data: BodyType<CreateInvestment> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createInvestment>>,
  TError,
  { data: BodyType<CreateInvestment> },
  TContext
> => {
  return useMutation(getCreateInvestmentMutationOptions(options));
};

/**
 * @summary Cancel an investment
 */
export const getCancelInvestmentUrl = (id: number) => {
  return `/api/investments/${id}`;
};

export const cancelInvestment = async (
  id: number,
  options?: RequestInit,
): Promise<CancelInvestment200> => {
  return customFetch<CancelInvestment200>(getCancelInvestmentUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getCancelInvestmentMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelInvestment>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelInvestment>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["cancelInvestment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelInvestment>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return cancelInvestment(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelInvestmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelInvestment>>
>;

export type CancelInvestmentMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Cancel an investment
 */
export const useCancelInvestment = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelInvestment>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof cancelInvestment>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getCancelInvestmentMutationOptions(options));
};
