/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Crypto Investment Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export interface CryptoAsset {
  id: number;
  symbol: string;
  name: string;
  price: number;
  priceChange24h: number;
  priceChangePercent24h: number;
  marketCap: number;
  volume24h: number;
  circulatingSupply: number;
  rank: number;
  logoUrl?: string | null;
}

export interface PortfolioHolding {
  id: number;
  symbol: string;
  name: string;
  quantity: number;
  averageBuyPrice: number;
  currentPrice: number;
  currentValue: number;
  profitLoss: number;
  profitLossPercent: number;
  logoUrl?: string | null;
}

export interface CreateHolding {
  symbol: string;
  quantity: number;
  averageBuyPrice: number;
}

export interface UpdateHolding {
  quantity?: number;
  averageBuyPrice?: number;
}

export interface WatchlistItem {
  id: number;
  symbol: string;
  name: string;
  price: number;
  priceChangePercent24h: number;
  logoUrl?: string | null;
}

export interface CreateWatchlistItem {
  symbol: string;
}

export type InvestmentPlanTier =
  (typeof InvestmentPlanTier)[keyof typeof InvestmentPlanTier];

export const InvestmentPlanTier = {
  starter: "starter",
  pro: "pro",
  vip: "vip",
} as const;

export interface InvestmentPlan {
  id: number;
  name: string;
  tier: InvestmentPlanTier;
  minAmount: number;
  maxAmount?: number | null;
  durationDays: number;
  roiPercent: number;
  description: string;
  features: string[];
}

export type UserInvestmentStatus =
  (typeof UserInvestmentStatus)[keyof typeof UserInvestmentStatus];

export const UserInvestmentStatus = {
  active: "active",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export interface UserInvestment {
  id: number;
  planId: number;
  planName: string;
  tier: string;
  amount: number;
  expectedReturn: number;
  roiPercent: number;
  durationDays: number;
  status: UserInvestmentStatus;
  startDate: string;
  endDate: string;
  daysRemaining: number;
  progressPercent: number;
}

export interface CreateInvestment {
  planId: number;
  amount: number;
}

export type GetMarketDataParams = {
  limit?: number;
  offset?: number;
};

export type GetMarketData200 = {
  data: CryptoAsset[];
  total: number;
};

export type GetPortfolio200 = {
  holdings: PortfolioHolding[];
  totalValue: number;
  totalProfitLoss: number;
  totalProfitLossPercent: number;
};

export type DeleteHolding200 = {
  success: boolean;
};

export type GetWatchlist200 = {
  items: WatchlistItem[];
};

export type RemoveFromWatchlist200 = {
  success: boolean;
};

export type GetInvestmentPlans200 = {
  plans: InvestmentPlan[];
};

export type GetUserInvestments200 = {
  investments: UserInvestment[];
  totalInvested: number;
  totalReturns: number;
  activeCount: number;
};

export type CancelInvestment200 = {
  success: boolean;
};
