/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Crypto Investment Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { InvestmentPlanTier } from "./investmentPlanTier";

export interface InvestmentPlan {
  id: number;
  name: string;
  tier: InvestmentPlanTier;
  minAmount: number;
  maxAmount?: number | null;
  durationDays: number;
  roiPercent: number;
  description: string;
  features: string[];
}
